#!/usr/bin/env python3

from datetime import datetime, timedelta

from coeapps import (
    get_driver,
    configure_logging,
    logging,
    new_parser,
    row_as_list_of_text,
    write_file,
    By,
    EC,
    TimeoutException,
    WebDriverWait,
)


def get_rows(driver, current):
    dispatch = "https://coeapps.eugene-or.gov/EPDDispatchLog/Search"
    driver.get(dispatch)

    # 07/01/2013 05:01:34 PM
    web_format = "%m/%d/%Y"
    format_time = current.strftime(web_format)
    iso_format = current.strftime("%Y%m%d")

    driver.implicitly_wait(1)
    date_from_box = driver.find_element(By.ID, "DateFrom")
    date_through_box = driver.find_element(By.ID, "DateThrough")
    submit_button = driver.find_element(By.XPATH, "//input[@type='submit']")

    date_from_box.send_keys(format_time)
    date_through_box.send_keys(format_time)
    submit_button.click()

    delay = 10
    try:
        wrapper = WebDriverWait(driver, delay).until(
            EC.presence_of_element_located((By.XPATH, "//table[@id='calls']"))
        )
        main_ = driver.find_element(By.ID, "main")

        if "Number of search results was reduced to 250" in main_.text:
            logging.warning("%s results truncated to 250", iso_format)
        table = driver.find_element(By.XPATH, "//table[@id='calls']")
        body = table.find_element(By.XPATH, ".//tbody")
        rows = body.find_elements(By.XPATH, ".//tr")

        summary = main_.find_elements(By.XPATH, "//div")[-3].text
        number_of_calls = int(summary.split(":")[1].strip())
        if number_of_calls != len(rows):
            logging.error(
                "%s expected %d calls, got %d",
                iso_format,
                number_of_calls,
                len(rows),
            )
        return [row_as_list_of_text(row, 1) for row in rows]
    except TimeoutException:
        logging.error("%s timeout", iso_format)
        return None


def main():
    parser = new_parser()
    args = parser.parse_args()

    start_y, start_m, start_d = (
        int(element) for element in args.start.split("-")
    )
    current = datetime(start_y, start_m, start_d)
    if args.end:
        end_y, end_m, end_d = (
            int(element) for element in args.end.split("-")
        )
        last = datetime(end_y, end_m, end_d)
    else:
        last = datetime.now()

    configure_logging("fetch-epd-log.log", args.log_level)
    logging.info("started with %s", args)

    day_format = "%Y%m%d"
    header = (
        "call_time",
        "dispatch_time",
        "incident_desc",
        "disposition",
        "event_number",
        "location",
        "priority",
        "case",
    )

    driver = get_driver()

    while current <= last:
        rows = get_rows(driver, current)
        write_file(rows, current.strftime(day_format), "epd", header)
        current = current + timedelta(days=1)

    driver.quit()


if __name__ == "__main__":
    main()
