epd_incident_descriptions = [
    'ATL Drunk Driver',
    'Abandoned Animal',
    'Abandoned Bike(s)',
    'Abandoned Prop.',
    'Abandoned Veh.',
    'Accident, Aircraft Injury',
    'Accident, Bike',
    'Accident, Industrial Injury',
    'Accident, Train Injury',
    'Accident, Vehicle-Bike',
    'Accident, Vehicle-Pedestrian',
    'Aircraft Problem Large',
    'Aircraft Problem Small',
    'Alarm',
    'Alarm, Hold Up',
    'Animal Abuse',
    'Animal Bite',
    'Animal Complaint',
    'Animal Cruelty',
    'Animal at Large',
    'Armed Subject(s)',
    'Arson',
    'Assault',
    'Assault 4',
    'Assault Public Safety Officer',
    'Assist Motorist',
    'Assist Outside Agency',
    'Assist Police Dept.',
    'Assist Public Works',
    'Assist Sheriff’s Office',
    'Assist State Police',
    'Attempt to Locate',
    'Bike Skateboard Complaint',
    'Blocked Alley',
    'Blocked Driveway',
    'Blocked Sidewalk',
    'Bomb Threat',
    'Broken Water Main',
    'Burglary',
    'Cancel ATL',
    'Careless Driving',
    'Check, Bar',
    'Christmas Light Theft/Damage',
    'Civil Stand By',
    'Controlled Substance Violation',
    'Criminal Mischief',
    'Criminal Mistreatment',
    'Criminal Trespass',
    'Custodial Interference',
    'DUII',
    'Damaged City Property',
    'Damaged County Property',
    'Dead Animal',
    'Disabled Vehicle(s)',
    'Disorderly Juvenile(s)',
    'Disorderly Party',
    'Disorderly Subject',
    'Disoriented Subject',
    'Dispute',
    'Dispute, Family',
    'Dog Bite',
    'Dog(s) at Large',
    'Dog(s), Barking',
    'Dog(s), Vicious',
    'Down Line',
    'Driving Complaint',
    'Driving While Suspended',
    'Drowning',
    'Emergency Message',
    'Escape',
    'Explosion',
    'Fight',
    'Fire, Apartment',
    'Fire, Trash Bin',
    'Foot Patrol',
    'Forged Check(s)',
    'Forged Prescription(s)',
    'Forgery',
    'Found Animal(s)',
    'Found Child(ren)',
    'Found Contraband',
    'Found Property',
    'Found Syringes',
    'Fraud',
    'Graffiti Calls',
    'Gun Shot Wound(s)',
    'Harassment',
    'Hazard, Safety',
    'Hazardous Material',
    'Hazardous Material Spill',
    'Hit & Run',
    'Illegal Burning',
    'Illegal Camping',
    'Illegal Discharge Firearms',
    'Illegal Dumping',
    'Illegal Fireworks',
    'Illegal Motorcycle(s)',
    'Illegal Parking',
    'Impersonating an Officer',
    'Impound Vehicle(s)',
    'In Possession of Narcotics',
    'Incomplete Call',
    'Injured Animal(s)',
    'Interfering with Police',
    'Intoxicated Subject(s)',
    'Juvenile Problem',
    'Liquor Violation',
    'Littering, Offensive',
    'Livestock at Large',
    'Locate Missing Person',
    'Location Runaway(s)',
    'Location Stolen Property',
    'Location Stolen Vehicle',
    'Lost Property',
    'Lost Subject',
    'Loud Construction',
    'Loud Noise',
    'Loud Party',
    'Menacing',
    'Minor in Possession of Tobacco',
    'Minor(s) in Possession',
    'Missing Juvenile(s)',
    'Missing Person(s)',
    'Missing Vehicle',
    'Motor Vehicle Injury',
    'Motor Vehicle No Injury',
    'Motor Vehicle Unknown',
    'Natural Gas Leak',
    'Nuisance Code Violations',
    'Nuisance Vehicle',
    'Officer-Involved Shooting',
    'Open Container',
    'Open Door',
    'Open Gate',
    'Open Window',
    'Overdue Subject(s)',
    'Person Stop',
    'Prostitution',
    'Prowler(s)',
    'Purse Snatch',
    'Pursuit',
    'Railroad Crossing Problem',
    'Reckless Burning',
    'Reckless Driving',
    'Reckless Endangering',
    'Recovered Stolen Property',
    'Recovered Stolen Vehicle',
    'Request Assistance',
    'Request Cover',
    'Request K-9',
    'Rescue Operation',
    'Road Closure',
    'Robbery',
    'Runaway(s), Cleared',
    'Runaway(s), Juvenile',
    'Seized Property',
    'Shoplift 3050',
    'Shoplifter(s)',
    'Shot(s) Fired',
    'Sign Down',
    'Speeding Motorcycle(s)',
    'Speeding Vehicle(s)',
    'Stab Wound',
    'Stab Wound(s)',
    'Stop Sign Down',
    'Storage on Street',
    'Subject Screaming',
    'Subject(s) Down',
    'Subpoena Service',
    'Suspicious Condition(s)',
    'Suspicious Subject(s)',
    'Suspicious Substance(s)',
    'Suspicious Vehicle(s)',
    'Switched Plates',
    'Theft',
    'Theft ID',
    'Theft by Deception',
    'Theft from Vehicle',
    'Theft of Services',
    'Theft, License Plate',
    'Theft, Mail',
    'Towed Vehicle',
    'Traffic Complaint',
    'Traffic Hazard',
    'Traffic Signal Malfunction',
    'Traffic Stop',
    'Tree Down',
    'Truck/Safety Checks',
    'Unattended Child(ren)',
    'Unauthorized Departure',
    'Unauthorized Use of Vehicle',
    'Unknown Problem',
    'Unlawful Vehicle Entry',
    'VIN Inspection',
    'Vehicle Release',
    'Vehicle in Water',
    'Violation of City Ordinance',
    'Walkaway',
    'Warrant Service',
    'Water Problem',
    'Weapon Offense',
    'Wrong Way Driver'
]
